module.exports = {
  env: {
    'browser': true,
    'jquery': true,
    'es6': true,
    'amd': true,
  },
  parser: 'babel-eslint',
  parserOptions: {
    'ecmaVersion': 7,
    'ecmaFeatures': {'jsx': true, 'classes': true},
  },
  plugins: ['react'],
  extends: ['eslint:recommended'],
  rules: {
    'accessor-pairs': 'error',
    'arrow-parens': ['error', 'always'],
    'arrow-spacing': ['error', {'before': true, 'after': true}],
    'block-spacing': ['error', 'always'],
    'brace-style': 'error',
    'camelcase': 'error',
    'capitalized-comments': ['error', 'always', {'ignoreConsecutiveComments': true}],
    'comma-dangle': ['error', 'always-multiline'],
    'comma-spacing': ['error', {'before': false, 'after': true}],
    'comma-style': ['error', 'last'],
    'constructor-super': 'error',
    'curly': ['error', 'multi-line'],
    'dot-location': ['error', 'property'],
    'eol-last': ['error', 'always'],
    'eqeqeq': ['error', 'smart'],
    'generator-star-spacing': ['error', {'before': true, 'after': true}],
    'handle-callback-err': 'off',
    'indent': ['error', 2, {'SwitchCase': 1}],
    'key-spacing': ['error', {'beforeColon': false, 'afterColon': true}],
    'keyword-spacing': [
      'error', {
        'after': false,
        'overrides': {
          'case': {'after': true},
          'const': {'after': true},
          'default': {'after': true},
          'let': {'after': true},
          'do': {'after': true},
          'else': {'after': true},
          'export': {'after': true},
          'from': {'after': true},
          'import': {'after': true},
          'return': {'after': true},
          'try': {'after': true},
        },
      },
    ],
    'linebreak-style': ['error', 'unix'],
    'new-cap': ['error', {'newIsCap': true, 'capIsNew': false}],
    'new-parens': 'error',
    'no-array-constructor': 'error',
    'no-caller': 'error',
    'no-class-assign': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-args': 'error',
    'no-dupe-class-members': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-eval': 'error',
    'no-ex-assign': 'error',
    'no-extend-native': 'error',
    'no-extra-bind': 'error',
    'no-extra-boolean-cast': 'error',
    'no-extra-parens': ['error', 'functions'],
    'no-fallthrough': 'error',
    'no-floating-decimal': 'error',
    'no-func-assign': 'error',
    'no-implied-eval': 'error',
    'no-inner-declarations': ['error', 'functions'],
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-iterator': 'error',
    'no-label-var': 'error',
    'no-labels': ['error', {'allowLoop': false, 'allowSwitch': false}],
    'no-lone-blocks': 'error',
    'no-mixed-spaces-and-tabs': 'error',
    'no-multi-spaces': 'error',
    'no-multi-str': 'error',
    'no-multiple-empty-lines': ['error', {'max': 1}],
    'no-native-reassign': 'error',
    'no-negated-in-lhs': 'error',
    'no-new': 'error',
    'no-new-func': 'error',
    'no-new-object': 'error',
    'no-new-require': 'error',
    'no-new-symbol': 'error',
    'no-new-wrappers': 'error',
    'no-obj-calls': 'error',
    'no-octal': 'error',
    'no-octal-escape': 'error',
    'no-param-reassign': 'error',
    'no-path-concat': 'error',
    'no-proto': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-return-assign': ['error', 'except-parens'],
    'no-self-assign': 'error',
    'no-self-compare': 'error',
    'no-sequences': 'error',
    'no-shadow-restricted-names': 'error',
    'no-spaced-func': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-throw-literal': 'error',
    'no-trailing-spaces': 'error',
    'no-undef-init': 'error',
    'no-unexpected-multiline': 'error',
    'no-unneeded-ternary': ['error', {'defaultAssignment': false}],
    'no-unreachable': 'error',
    'no-unused-vars': 'error',
    'no-undef': 'off',
    'no-useless-call': 'error',
    'no-useless-constructor': 'error',
    'no-var': 'error',
    'no-with': 'error',
    'operator-linebreak': ['error', 'after'],
    'padding-line-between-statements': [
      'error',
      {'blankLine': "always", 'prev': ['multiline-const', 'multiline-let', 'multiline-var', 'multiline-expression', 'multiline-block-like'], 'next': '*'},
      {'blankLine': 'always', 'prev': '*', 'next': ['multiline-const', 'multiline-let', 'multiline-var', 'multiline-expression', 'multiline-block-like']},
    ],
    'padded-blocks': ['error', 'never'],
    'prefer-arrow-callback': 'error',
    'prefer-const': 'error',
    'quotes': ['error', 'single'],
    'semi': ['error', 'always'],
    'semi-spacing': ['error', {'before': false, 'after': true}],
    'space-before-blocks': ['error', 'always'],
    'space-before-function-paren': ['error', 'never'],
    'space-in-parens': ['error', 'never'],
    'space-infix-ops': 'off',
    'space-unary-ops': ['error', {'words': true, 'nonwords': false}],
    'spaced-comment': ['error', 'always', {'markers': ['global', 'globals', 'eslint', 'eslint-disable']}],
    'template-curly-spacing': ['error', 'never'],
    'use-isnan': 'error',
    'valid-typeof': 'error',
    'wrap-iife': ['error', 'any'],
    'yield-star-spacing': ['error', 'both'],
    'yoda': ['error', 'never'],
    'react/jsx-uses-vars': 'error',
    'react/jsx-uses-react': 'error',
  },
};
